=== mulinski/SpatialNet/SpatialNet/vignettes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="urn:spatialnet" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="vignettes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="vignette" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="inputType" name="input" maxOccurs="unbounded" minOccurs="0"/>
              <xs:element type="constraintsType" name="constraints" minOccurs="0"/>
              <xs:element type="outputType" name="output" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="abstract" use="optional"/>
            <xs:attribute type="xs:string" name="name" use="optional"/>
            <xs:attribute type="xs:string" name="parent" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="inputType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="frame" use="optional"/>
        <xs:attribute type="xs:string" name="lexUnit" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="constraintsType">
    <xs:sequence>
      <xs:element type="orType" name="or" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="type-constraintType" name="type-constraint" maxOccurs="unbounded"
        minOccurs="0"/>
      <xs:element type="assertion-constraintType" name="assertion-constraint" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="orType">
    <xs:sequence maxOccurs="unbounded" minOccurs="0">
      <xs:element type="orType" name="or" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="assertion-constraintType" name="assertion-constraint"/>
      <xs:element type="type-constraintType" name="type-constraint"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="type-constraintType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="FE" use="optional"/>
        <xs:attribute type="xs:string" name="type" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="assertion-constraintType">
    <xs:sequence>
      <xs:element type="mapType" name="map" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="relation" use="optional"/>
  </xs:complexType>

  <xs:complexType name="outputType" mixed="true">
    <xs:sequence>
      <xs:element type="mapType" name="map" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="parent" use="optional"/>
    <xs:attribute type="xs:string" name="relation" use="optional"/>
  </xs:complexType>

  <xs:complexType name="mapType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="FE" use="optional"/>
        <xs:attribute type="xs:string" name="arg" use="optional"/>
        <xs:attribute type="xs:string" name="value" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== mulinski/SpatialNet/SpatialNet/vignettes/orientation-intrinsic-vignettes.xml
<vignettes xmlns="urn:spatialnet"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:spatialnet ../vignettes.xsd">

  <!-- parent vignette for orientation adjectives -->
  <vignette abstract="true" name="orientation">
    <input frame="Orientation"/>
    <constraints>
      <type-constraint FE="Entity" type="physical-entity.n"/>
    </constraints>
    <output name="orientation">
      <map FE="Entity" arg="entity"/>
    </output>
  </vignette>

  <!--orientation adjectives (upside-down, supine) TODO: sideways, rightside-up etc-->
  <vignette name="supine" parent="orientation">
    <input frame="Orientation" lexUnit="supine.a"/>
    <output relation="gfx.supine.r" parent="orientation"/>
  </vignette>
  <vignette name="upside-down" parent="orientation">
    <input frame="Orientation" lexUnit="upside-down.a"/>
    <output relation="gfx.upside-down.r" parent="orientation"/>
  </vignette>
  <vignette name="upright" parent="orientation">
    <input frame="Orientation" lexUnit="upright.a"/>
    <output relation="gfx.upright.r" parent="orientation"/>
  </vignette>
</vignettes>

=== mulinski/SpatialNet/SpatialNet/vignettes/embedded-in-vignettes.xml
<vignettes xmlns="urn:spatialnet"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:spatialnet ../vignettes.xsd">
  <!-- X embedded in (top surface of) Y -->
  <vignette name="embedded-in" parent="spatial-relation">
    <input frame="Containing" lexUnit="in.adp"/>
    <input frame="Containing" lexUnit="inside.adp"/>
    <input frame="Containing" lexUnit="within.adp"/>
    <constraints>
      <or>
        <type-constraint FE="Ground" type="top-surface-tagged-item.n"/>
        <assertion-constraint relation="gfx.spatial-tag.r">
          <map arg="object" FE="Ground"/>
          <map arg="tag-type" value="top-surface-tag.n"/>
        </assertion-constraint>
      </or>
    </constraints>
    <output relation="gfx.embedded-in.r" parent="spatial-relation-mixin"/>
  </vignette>

  <!-- X embedded some distance in Y -->
  <vignette name="embedded-in" parent="spatial-relation-with-distance">
    <input frame="Containing" lexUnit="in.adp"/>
    <!--input frame="Containing" lexUnit="inside.adp"/-->
    <output relation="gfx.embedded-in.r" parent="spatial-relation-mixin"/>
  </vignette>

  <!-- X embedded in Y -->
  <vignette name="embedded-in-default" parent="spatial-relation">
    <input frame="Containing" lexUnit="in.adp"/>
    <input frame="Containing" lexUnit="inside.adp"/>
    <input frame="Containing" lexUnit="within.adp"/>
    <output relation="gfx.embedded-in.r" parent="spatial-relation-mixin"/>
  </vignette>
</vignettes>

=== mulinski/SpatialNet/SpatialNet/vignettes/oriented-toward-vignettes.xml
<vignettes xmlns="urn:spatialnet"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:spatialnet ../vignettes.xsd">

  <!-- parent vignette for X oriented toward  something -->
  <vignette abstract="true" name="orientation-toward">
    <input frame="Orientation"/>
    <constraints>
      <type-constraint FE="Entity" type="physical-entity.n"/>
    </constraints>
    <output name="orientation-toward" relation="gfx.orientation-toward.r">
      <map FE="Entity" arg="figure"/>
    </output>
  </vignette>


  <!-- X faces toward Y -->
  <vignette name="face-toward" parent="orientation-toward">
    <input frame="Orientation" lexUnit="face.v"/>
    <input frame="Orientation" lexUnit="toward.adp"/>
    <input frame="Orientation" lexUnit="to.adp"/>
    <constraints>
      <or>
        <type-constraint FE="Target" type="physical-entity.n"/>
        <type-constraint FE="Target" type="direction.n"/>
      </or>
    </constraints>
    <output parent="orientation-toward">
      <map FE="Target" arg="ground"/>
    </output>
  </vignette>

  <!-- X faces (some direction) -->
  <vignette name="face-forward" parent="orientation-toward">
    <input frame="Orientation" lexUnit="forward.adv"/>
    <output parent="orientation-toward">
      <map value="forward-direction.n" arg="ground"/>
    </output>
  </vignette>
  <vignette name="face-backward" parent="orientation-toward">
    <input frame="Orientation" lexUnit="backward.adv"/>
    <output parent="orientation-toward">
      <map value="backward-direction.n" arg="ground"/>
    </output>
  </vignette>
  <vignette name="face-down" parent="orientation-toward">
    <input frame="Orientation" lexUnit="down.adp"/>
    <input frame="Orientation" lexUnit="face-down.a"/>
    <output parent="orientation-toward">
      <map value="down-direction.n" arg="ground"/>
    </output>
  </vignette>
  <vignette name="face-left" parent="orientation-toward">
    <input frame="Orientation" lexUnit="left.v"/>
    <output parent="orientation-toward">
      <map value="left-direction.n" arg="ground"/>
    </output>
  </vignette>
  <vignette name="face-right" parent="orientation-toward">
    <input frame="Orientation" lexUnit="right.adv"/>
    <output parent="orientation-toward">
      <map value="right-direction.n" arg="ground"/>
    </output>
  </vignette>
  <vignette name="face-up" parent="orientation-toward">
    <input frame="Orientation" lexUnit="up.adp"/>
    <input frame="Orientation" lexUnit="face-up.a"/>
    <output parent="orientation-toward">
      <map value="up-direction.n" arg="ground"/>
    </output>
  </vignette>
  <vignette name="face-east" parent="orientation-toward">
    <input frame="Orientation" lexUnit="east.a"/>
    <output parent="orientation-toward">
      <map value="east.n" arg="ground"/>
    </output>
  </vignette>
  <vignette name="face-north" parent="orientation-toward">
    <input frame="Orientation" lexUnit="north.adv"/>
    <output parent="orientation-toward">
      <map value="north.n" arg="ground"/>
    </output>
  </vignette>
  <vignette name="face-northeast" parent="orientation-toward">
    <input frame="Orientation" lexUnit="northeast.adv"/>
    <output parent="orientation-toward">
      <map value="northeast.n" arg="ground"/>
    </output>
  </vignette>
  <vignette name="face-northwest" parent="orientation-toward">
    <input frame="Orientation" lexUnit="northwest.adv"/>
    <output parent="orientation-toward">
      <map value="northwest.n" arg="ground"/>
    </output>
  </vignette>
  <vignette name="face-south" parent="orientation-toward">
    <input frame="Orientation" lexUnit="south.adv"/>
    <output parent="orientation-toward">
      <map value="south.n" arg="ground"/>
    </output>
  </vignette>

</vignettes>

=== mulinski/SpatialNet/SpatialNet/vignettes/lean-on-vignettes.xml
<vignettes xmlns="urn:spatialnet"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:spatialnet ../vignettes.xsd">

  <!-- X leans on/against Y -->
  <!-- TODO could update this to use new SGPs? -->
  <vignette name="lean-on" parent="spatial-relation">
    <input frame="Spatial_contact" lexUnit="lean.v"/>
    <input frame="Spatial_contact" lexUnit="tilt.v"/>
    <output relation="gfx.tilt-toward.r">
      <map FE="Figure" arg="figure"/>
      <map arg="ground" FE="Ground"/>
    </output>
    <output relation="gfx.next-to.r">
      <map FE="Figure" arg="figure"/>
      <map arg="ground" FE="Ground"/>
    </output>
  </vignette>

  <!-- X leans/tilts toward Y -->
  <vignette name="lean-toward">
    <input frame="Orientation" lexUnit="lean.v"/>
    <input frame="Orientation" lexUnit="tilt.v"/>
    <constraints>
      <or>
        <type-constraint FE="Target" type="physical-entity.n"/>
        <type-constraint FE="Target" type="direction.n"/>
      </or>
    </constraints>
    <output relation="gfx.tilt-toward.r" name="tilt-toward">
      <map FE="Entity" arg="figure"/>
      <map arg="ground" FE="Target"/>
    </output>
  </vignette>

  <!-- X leans/tilts (some distance) toward Y -->
  <vignette name="lean-with-distance" parent="lean-toward">
    <input frame="Orientation" lexUnit="lean.v"/>
    <input frame="Orientation" lexUnit="tilt.v"/>
    <constraints>
      <or>
        <type-constraint FE="Target" type="physical-entity.n"/>
        <type-constraint FE="Target" type="direction.n"/>
      </or>
      <type-constraint FE="Unit" type="distance-unit.n"/>
    </constraints>
    <output parent="tilt-toward">
      <map FE="Count" arg="measure-cardinality"/>
      <map FE="Unit" arg="measure-unit"/>
    </output>
  </vignette>

</vignettes>

=== mulinski/SpatialNet/SpatialNet/vignettes/in-area.xml
<vignettes xmlns="urn:spatialnet"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:spatialnet ../vignettes.xsd">
<!-- TODO: in the room => on the floor of the room -->
  <vignette name="in-area" parent="spatial-relation">
    <input frame="Containing" lexUnit="in.adp"/>
    <input frame="Locative_relation" lexUnit="middle.n"/>
    <input frame="Locative_relation" lexUnit="center.n"/>
    <constraints>
      <!--or>
        <type-constraint FE="Ground" type="3d-ground-object.n"/-->
      <!--type-constraint FE="Ground" type="land-area.n"/-->
      <!--/or-->
      <type-constraint FE="Ground" type="location/locale/place/spot.n"/>
    </constraints>
    <output relation="gfx.on-top-surface.r" parent="spatial-relation-mixin"/>
  </vignette>
</vignettes>

=== mulinski/SpatialNet/SpatialNet/vignettes/adjacency-vignettes.xml
<vignettes xmlns="urn:spatialnet"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:spatialnet ../vignettes.xsd">

  <!-- X at/near Y -->
  <vignette name="locally-at" parent="spatial-relation">
    <input frame="Adjacency" lexUnit="at.adp"/>
    <input frame="Adjacency" lexUnit="near.adp"/>
    <output relation="gfx.locally-at.r" parent="spatial-relation-mixin"/>
  </vignette>

  <!-- TODO: add from VigNet :we.nearby.r :we.nearer.r :we.near-to.r :we.nearer-to.r
        :we.near-by.r :we.nearest-to.r
        :we.closer-to.r :we.closest-to.r :we.close-to.r
        :we.closest-by.r :we.close-by.r -->

  <!-- X next to/beside/close to Y -->
  <vignette name="next-to" parent="spatial-relation">
    <input frame="Adjacency" lexUnit="next_to.adp"/>
    <input frame="Adjacency" lexUnit="beside.adp"/>
    <input frame="Adjacency" lexUnit="close_to.adp"/>
    <output relation="gfx.next-to.r" parent="spatial-relation-mixin"/>
  </vignette>
</vignettes>

=== mulinski/SpatialNet/SpatialNet/vignettes/directional-vignettes.xml
<vignettes xmlns="urn:spatialnet"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:spatialnet ../vignettes.xsd">

  <!-- X left/right of Y -->
  <vignette name="left-of" parent="spatial-relation">
    <input frame="Non-gradable_proximity" lexUnit="left.n"/>
    <output relation="gfx.left-of.r" parent="spatial-relation-mixin"/>
  </vignette>
  <vignette name="left-of-with-distance" parent="spatial-relation-with-distance">
    <input frame="Non-gradable_proximity" lexUnit="left.n"/>
    <output relation="gfx.left-of.r" parent="spatial-relation-mixin"/>
  </vignette>

  <vignette name="right-of" parent="spatial-relation">
    <input frame="Non-gradable_proximity" lexUnit="right.n"/>
    <output relation="gfx.right-of.r" parent="spatial-relation-mixin"/>
  </vignette>
  <vignette name="right-of-with-distance" parent="spatial-relation-with-distance">
    <input frame="Non-gradable_proximity" lexUnit="right.n"/>
    <output relation="gfx.right-of.r" parent="spatial-relation-mixin"/>
  </vignette>

  <!-- X in front of/behind Y -->
  <vignette name="in-front-of" parent="spatial-relation">
    <input frame="Non-gradable_proximity" lexUnit="in_front_of.adp"/>
    <input frame="Non-gradable_proximity" lexUnit="ahead_of.adv"/>
    <output relation="gfx.in-front-of.r" parent="spatial-relation-mixin"/>
  </vignette>
  <vignette name="in-front-of-with-distance" parent="spatial-relation-with-distance">
    <input frame="Non-gradable_proximity" lexUnit="in_front_of.adp"/>
    <input frame="Non-gradable_proximity" lexUnit="ahead_of.adv"/>
    <output relation="gfx.in-front-of.r" parent="spatial-relation-mixin"/>
  </vignette>

  <vignette name="behind" parent="spatial-relation">
    <input frame="Non-gradable_proximity" lexUnit="behind.adp"/>
    <input frame="Non-gradable_proximity" lexUnit="beyond.adp"/>
    <output relation="gfx.behind.r" parent="spatial-relation-mixin"/>
  </vignette>
  <vignette name="behind-with-distance" parent="spatial-relation-with-distance">
    <input frame="Non-gradable_proximity" lexUnit="behind.adp"/>
    <input frame="Non-gradable_proximity" lexUnit="beyond.adp"/>
    <output relation="gfx.behind.r" parent="spatial-relation-mixin"/>
  </vignette>

  <!-- X  above Y -->
  <vignette name="above" parent="spatial-relation">
    <input frame="Directional_locative_relation" lexUnit="above.adp"/>
    <input frame="Non-gradable_proximity" lexUnit="over.adp"/>
    <output relation="gfx.above.r" parent="spatial-relation-mixin"/>
  </vignette>
  <!-- X some distance above Y -->
  <vignette name="above-with-distance" parent="spatial-relation-with-distance">
    <input frame="Directional_locative_relation" lexUnit="above.adp"/>
    <input frame="Non-gradable_proximity" lexUnit="over.adp"/>
    <output relation="gfx.above.r" parent="spatial-relation-mixin"/>
  </vignette>

  <!-- X some distance below Y -->
  <vignette name="below-with-distance" parent="spatial-relation-with-distance">
    <input frame="Directional_locative_relation" lexUnit="below.adp"/>
    <output relation="gfx.below.r" parent="spatial-relation-mixin"/>
  </vignette>
  <!-- X below/under Y -->
  <vignette name="below-default" parent="spatial-relation">
    <input frame="Directional_locative_relation" lexUnit="below.adp"/>
    <input frame="Non-gradable_proximity" lexUnit="under.adp"/>
    <input frame="Non-gradable_proximity" lexUnit="underneath.adp"/>
    <output relation="gfx.below.r" parent="spatial-relation-mixin"/>
  </vignette>


</vignettes>

=== mulinski/SpatialNet/SpatialNet/vignettes/part-of.xml
<vignettes xmlns="urn:spatialnet"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:spatialnet ../vignettes.xsd">
<!-- part/whole relations - how to integrate this better with spatial vignettes? -->
<!-- TODO:  spatial relation vignettes should check the type of the whole, not the part -->
<!-- TODO: fix part/whole stuff so it actually works -->
  <vignette name="part-of">
    <input frame="Part_orientational" lexUnit="DEFAULT"/>
    <constraints>
      <or>
        <type-constraint FE="Part" type="generic-part.n"/>
        <assertion-constraint relation="we.part-of.r">
          <map FE="Part" arg="part"/>
          <map FE="Whole" arg="whole"/>
        </assertion-constraint>
      </or>
      <type-constraint FE="Part" type="part-specifier.n"/>
    </constraints>
    <output relation="we.generic-part-of.r">
      <map FE="Part" arg="part"/>
      <map FE="Whole" arg="whole"/>
    </output>
  </vignette>
</vignettes>
