=== mulinski/SpatialNet/SpatialNet/vignettes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="urn:spatialnet" attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="vignettes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="vignette" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="inputType" name="input" maxOccurs="unbounded" minOccurs="0"/>
              <xs:element type="constraintsType" name="constraints" minOccurs="0"/>
              <xs:element type="outputType" name="output" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="abstract" use="optional"/>
            <xs:attribute type="xs:string" name="name" use="optional"/>
            <xs:attribute type="xs:string" name="parent" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="inputType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="frame" use="optional"/>
        <xs:attribute type="xs:string" name="lexUnit" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="constraintsType">
    <xs:sequence>
      <xs:element type="orType" name="or" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="type-constraintType" name="type-constraint" maxOccurs="unbounded"
        minOccurs="0"/>
      <xs:element type="assertion-constraintType" name="assertion-constraint" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="orType">
    <xs:sequence maxOccurs="unbounded" minOccurs="0">
      <xs:element type="orType" name="or" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element type="assertion-constraintType" name="assertion-constraint"/>
      <xs:element type="type-constraintType" name="type-constraint"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="type-constraintType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="FE" use="optional"/>
        <xs:attribute type="xs:string" name="type" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="assertion-constraintType">
    <xs:sequence>
      <xs:element type="mapType" name="map" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="relation" use="optional"/>
  </xs:complexType>

  <xs:complexType name="outputType" mixed="true">
    <xs:sequence>
      <xs:element type="mapType" name="map" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
    <xs:attribute type="xs:string" name="parent" use="optional"/>
    <xs:attribute type="xs:string" name="relation" use="optional"/>
  </xs:complexType>

  <xs:complexType name="mapType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="FE" use="optional"/>
        <xs:attribute type="xs:string" name="arg" use="optional"/>
        <xs:attribute type="xs:string" name="value" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
</xs:schema>

=== mulinski/SpatialNet/SpatialNet/vignettes/on-surface-vignettes.xml
<vignettes xmlns="urn:spatialnet"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:spatialnet ../vignettes.xsd">

  <!-- X on (front of) Y -->
  <vignette name="on-front-surface" parent="spatial-relation">
    <input frame="On_surface" lexUnit="on.adp"/>
    <input frame="Spatial_contact" lexUnit="hang.v"/>
    <constraints>
      <or>
        <assertion-constraint relation="gfx.preferred-surfaces.r">
          <map arg="entity" FE="Ground"/>
          <map arg="surface" value="front-surface"/>
        </assertion-constraint>
        <type-constraint FE="Ground" type="f-vertical-surface.n"/>
        <!--type-constraint FE="Ground" type="front-surface-tagged-item"/-->
      </or>
      <type-constraint FE="Figure" type="f-wall-item.n"/>
    </constraints>
    <output relation="gfx.on-front-surface.r" parent="spatial-relation-mixin"/>
  </vignette>
  <vignette name="on-front-surface-wall-item" parent="spatial-relation">
    <input frame="On_surface" lexUnit="on.adp"/>
    <input frame="Spatial_contact" lexUnit="hang.v"/>
    <constraints>
      <type-constraint FE="Figure" type="f-wall-item.n"/>
    </constraints>
    <output relation="gfx.on-front-surface.r" parent="spatial-relation-mixin"/>
  </vignette>
  <!-- explicitly specify the front -->
  <!-- TODO: does hanging always imply front? -->
  <vignette name="on-front-surface-no-constraints" parent="spatial-relation">
    <input frame="On_surface" lexUnit="front.n"/>
    <input frame="Spatial_contact" lexUnit="hang.v"/>
    <output relation="gfx.on-front-surface.r" parent="spatial-relation-mixin"/>
  </vignette>

  <!-- "the X on the ceiling; the X in the middle of the ceiling"; uses affordances -->
  <vignette name="on-bottom-surface" parent="spatial-relation">
    <input frame="On_surface" lexUnit="on.adp"/>
    <input frame="Locative_relation" lexUnit="middle.n"/>
    <input frame="Locative_relation" lexUnit="center.n"/>
    <constraints>
      <or>
        <type-constraint FE="Ground" type="ceiling.n"/>
        <assertion-constraint relation="gfx.preferred-surfaces.r">
          <map arg="entity" FE="Ground"/>
          <map arg="surface" value="bottom-surface"/>
        </assertion-constraint>
      </or>
    </constraints>
    <output relation="gfx.on-bottom-surface.r" parent="spatial-relation-mixin"/>
  </vignette>
  <!-- "X on the bottom/underside of the Y" -->
  <vignette name="on-bottom-surface-no-constraints" parent="spatial-relation">
    <input frame="On_surface" lexUnit="bottom.n"/>
    <input frame="On_surface" lexUnit="underside.n"/>
    <output relation="gfx.on-bottom-surface.r" parent="spatial-relation-mixin"/>
  </vignette>

  <!-- "the X on the table; the X in the middle of the table" -->
  <vignette name="on-top-surface" parent="spatial-relation">
    <input frame="On_surface" lexUnit="on.adp"/>
    <input frame="Locative_relation" lexUnit="middle.n"/>
    <input frame="Locative_relation" lexUnit="center.n"/>
    <constraints>
      <assertion-constraint relation="gfx.preferred-surfaces.r">
        <map arg="entity" FE="Ground"/>
        <map arg="surface" value="top-surface"/>
      </assertion-constraint>
    </constraints>
    <output relation="gfx.on-top-surface.r" parent="spatial-relation-mixin"/>
  </vignette>
  <!--  X on top of Y -->
  <vignette name="on-top-surface-no-constraints" parent="spatial-relation">
    <input frame="On_surface" lexUnit="on_top_of.adp"/>
    <input frame="On_surface" lexUnit="top.n"/>
    <output relation="gfx.on-top-surface.r" parent="spatial-relation-mixin"/>
  </vignette>


  <!-- fallback for "on" -->
  <vignette name="default-on" parent="spatial-relation">
    <input frame="On_surface" lexUnit="on.adp"/>
    <output relation="gfx.on-top-surface.r" parent="spatial-relation-mixin"/>
  </vignette>

</vignettes>

=== mulinski/SpatialNet/SpatialNet/vignettes/containing-vignettes.xml
<vignettes xmlns="urn:spatialnet"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="urn:spatialnet ../vignettes.xsd">

  <!-- cat under the table, person sitting under tree -->
  <vignette name="under-canopy" parent="spatial-relation">
    <input frame="Directional_locative_relation" lexUnit="below.adp"/>
    <input frame="Non-gradable_proximity" lexUnit="under.adp"/>
    <input frame="Non-gradable_proximity" lexUnit="underneath.adp"/>
    <constraints>
      <or>
        <type-constraint FE="Ground" type="canopy-tagged-item.n"/>
        <assertion-constraint relation="gfx.spatial-tag.r">
          <map arg="object" FE="Ground"/>
          <map arg="tag-type" value="canopy-tag.n"/>
        </assertion-constraint>
      </or>
    </constraints>
    <output relation="gfx.under-canopy-cup.r" parent="spatial-relation-mixin"/>
  </vignette>

  <!-- flower in vase -->
  <vignette name="stem-in-cup" parent="spatial-relation">
    <input frame="Containing" lexUnit="in.adp"/>
    <!--input frame="Containing" lexUnit="inside.adp"/-->
    <constraints>
      <or>
        <type-constraint FE="Ground" type="cupped-tagged-item.n"/>
        <assertion-constraint relation="gfx.spatial-tag.r">
          <map arg="object" FE="Ground"/>
          <map arg="tag-type" value="cup-tag.n"/>
        </assertion-constraint>
      </or>
      <assertion-constraint relation="gfx.spatial-tag.r">
        <map arg="object" FE="Figure"/>
        <map arg="tag-type" value="stem-tag.n"/>
      </assertion-constraint>
    </constraints>
    <output relation="gfx.stem-in-cup.r" parent="spatial-relation-mixin"/>
  </vignette>

  <!-- apple in bowl -->
  <vignette name="in-cup" parent="spatial-relation">
    <input frame="Containing" lexUnit="in.adp"/>
    <input frame="Containing" lexUnit="inside.adp"/>
    <input frame="Containing" lexUnit="within.adp"/>
    <constraints>
      <or>
        <type-constraint FE="Ground" type="cupped-tagged-item.n"/>
        <assertion-constraint relation="gfx.spatial-tag.r">
          <map arg="object" FE="Ground"/>
          <map arg="tag-type" value="cup-tag.n"/>
        </assertion-constraint>
      </or>
    </constraints>
    <output relation="gfx.in-cup.r" parent="spatial-relation-mixin"/>
  </vignette>

  <!-- rabbit in cage -->
  <vignette name="in-enclosure" parent="spatial-relation">
    <input frame="Containing" lexUnit="in.adp"/>
    <input frame="Containing" lexUnit="inside.adp"/>
    <input frame="Containing" lexUnit="within.adp"/>
    <constraints>
      <or>
        <type-constraint FE="Ground" type="enclosure-tagged-item.n"/>
        <assertion-constraint relation="gfx.spatial-tag.r">
          <map arg="object" FE="Ground"/>
          <map arg="tag-type" value="enclosure-tag.n"/>
        </assertion-constraint>
      </or>
    </constraints>
    <output relation="gfx.in-3d-enclosure.r" parent="spatial-relation-mixin"/>
  </vignette>

  <!-- bird hiding in the bush -->
  <vignette name="in-entanglement" parent="spatial-relation">
    <input frame="Containing" lexUnit="in.adp"/>
    <input frame="Containing" lexUnit="inside.adp"/>
    <input frame="Containing" lexUnit="within.adp"/>
    <constraints>
      <or>
        <type-constraint FE="Ground" type="entangled-tagged-item.n"/>
        <assertion-constraint relation="gfx.spatial-tag.r">
          <map arg="object" FE="Ground"/>
          <map arg="tag-type" value="entangled-tag.n"/>
        </assertion-constraint>
      </or>
    </constraints>
    <output relation="gfx.in-entanglement.r" parent="spatial-relation-mixin"/>
  </vignette>


</vignettes>
