=== mulinski/SpatialNet/SpatialNet/frames/frame.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" targetNamespace="urn:spatialnet" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="frame">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="parentType" name="parent" minOccurs="0"/>
        <xs:element type="FEType" name="FE" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element type="valencePatternsType" name="valencePatterns" minOccurs="0"/>
        <xs:element type="lexUnitType" name="lexUnit" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute type="xs:string" name="name"/>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="parentType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="FEType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="name" use="optional"/>
        <xs:attribute type="xs:string" name="parent" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:complexType name="valencePatternsType">
    <xs:sequence>
      <xs:element type="patternType" name="pattern" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="patternType">
    <xs:sequence>
      <xs:element type="depType" name="dep"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="id" use="optional"/>
  </xs:complexType>

  <xs:complexType name="depType" mixed="true">
    <xs:choice maxOccurs="unbounded" minOccurs="0">
      <xs:element type="depType" name="dep"/>
      <xs:element type="exclude-depType" name="exclude-dep"/>
    </xs:choice>
    <xs:attribute type="xs:string" name="FE" use="optional"/>
    <xs:attribute type="xs:string" name="pred" use="optional"/>
    <xs:attribute type="xs:string" name="reln" use="optional"/>
    <xs:attribute type="xs:string" name="lexUnit" use="optional"/>
    <xs:attribute type="xs:string" name="order" use="optional"/>
    <xs:attribute type="xs:string" name="tag" use="optional"/>
    <xs:attribute type="xs:string" name="word" use="optional"/>
    <xs:attribute type="xs:string" name="not-lemma" use="optional"/>
  </xs:complexType>

  <xs:complexType name="exclude-depType" mixed="true">
    <xs:sequence>
      <xs:element type="depType" name="dep"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="reln" use="optional"/>
    <xs:attribute type="xs:string" name="FE" use="optional"/>
    <xs:attribute type="xs:string" name="pred" use="optional"/>
    <xs:attribute type="xs:string" name="lexUnit" use="optional"/>
    <xs:attribute type="xs:string" name="order" use="optional"/>
    <xs:attribute type="xs:string" name="tag" use="optional"/>
    <xs:attribute type="xs:string" name="word" use="optional"/>
    <xs:attribute type="xs:string" name="not-lemma" use="optional"/>
  </xs:complexType>

  <xs:complexType name="lexemeType" mixed="true">
    <xs:sequence>
      <xs:element type="depType" name="dep" minOccurs="0"/>
      <xs:element type="exclude-depType" name="exclude-dep"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="tag" use="optional"/>
    <xs:attribute type="xs:string" name="word" use="optional"/>
    <xs:attribute type="xs:string" name="lemma" use="optional"/>
    <xs:attribute type="xs:string" name="order" use="optional"/>
  </xs:complexType>
  <xs:complexType name="use-patternType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute type="xs:string" name="id" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>
  <xs:complexType name="lexUnitType">
    <xs:sequence>
      <xs:element type="lexemeType" name="lexeme"/>
      <xs:element type="use-patternType" name="use-pattern" maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="name" use="optional"/>
  </xs:complexType>

</xs:schema>

=== mulinski/SpatialNet/SpatialNet/frames/On_surface.xml
<frame name="On_surface" xmlns="urn:spatialnet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:spatialnet frame.xsd">
  <parent name="Spatial_contact"/>
  <FE name="Figure"/>
  <FE name="Ground"/>
  <valencePatterns>
    <!-- fig is on X of the ground -->
    <pattern id="21">
      <dep lexUnit="true" pred="true" order="3">
        <dep FE="Figure" reln="nsubj" order="1"/>
        <dep reln="case" word="on" order="2"/>
        <dep reln="nmod" FE="Ground" order="5">
          <dep reln="case" word="of" order="4"/>
        </dep>
      </dep>
    </pattern>
  </valencePatterns>
  <lexUnit name="on_top_of.adp">
    <lexeme tag="ADP" word="on" order="1">
      <dep word="top" reln="mwe" order="2"/>
      <dep word="of" reln="mwe" order="3"/>
    </lexeme>
    <use-pattern id="1"/>
    <use-pattern id="2"/>
  </lexUnit>
  <lexUnit name="on.adp">
    <lexeme tag="ADP" word="on">
      <exclude-dep reln="mwe"/>
    </lexeme>
    <use-pattern id="1"/>
    <use-pattern id="2"/>
  </lexUnit>
  <lexUnit name="front.n">
    <lexeme tag="NOUN" word="front"/>
    <use-pattern id="21"/>
  </lexUnit>
  <lexUnit name="back.n">
    <lexeme tag="NOUN" word="back"/>
    <use-pattern id="21"/>
  </lexUnit>
  <lexUnit name="side.n">
    <lexeme tag="NOUN" word="side"/>
    <use-pattern id="21"/>
  </lexUnit>
  <lexUnit name="bottom.n">
    <lexeme tag="NOUN" word="bottom"/>
    <use-pattern id="21"/>
  </lexUnit>
  <lexUnit name="underside.n">
    <lexeme tag="NOUN" word="underside"/>
    <use-pattern id="21"/>
  </lexUnit>
  <lexUnit name="top.n">
    <lexeme tag="NOUN" word="top"/>
    <use-pattern id="21"/>
  </lexUnit>
</frame>

=== mulinski/SpatialNet/SpatialNet/frames/Containing.xml
<frame name="Containing" xmlns="urn:spatialnet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:spatialnet frame.xsd">
  <parent name="Locative_relation"/>
  <FE name="Figure"/>
  <FE name="Ground"/>
  <lexUnit name="in.adp">
    <lexeme tag="ADP" word="in"/>
    <use-pattern id="1"/>
    <use-pattern id="2"/>
    <use-pattern id="20"/>
  </lexUnit>
  <lexUnit name="inside.adp">
    <lexeme tag="ADP" word="inside"/>
    <use-pattern id="1"/>
    <use-pattern id="2"/>
  </lexUnit>
  <lexUnit name="within.adp">
    <lexeme tag="ADP" word="within"/>
    <use-pattern id="1"/>
    <use-pattern id="2"/>
  </lexUnit>
  <!--TODO: "into"-->
</frame>

=== mulinski/SpatialNet/SpatialNet/frames/Orientation.xml
<!-- TODO: subdivide into intrinsic orientation (adjectives e.g. supine upside-down etc) vs.
     relative to another entity (toward Y, away from Y, etc.) -->
<frame name="Orientation" xmlns="urn:spatialnet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:spatialnet frame.xsd">
  <FE name="Entity"/>
  <FE name="Orientation"/>
  <FE name="Distance"/>
  <FE name="Target"/>
  <valencePatterns>
    <!-- the X entity -->
    <pattern id="8">
      <dep FE="Entity" tag="NOUN" order="2">
        <dep FE="Orientation" pred="true" reln="compound" lexUnit="true" order="1"/>
      </dep>
    </pattern>
    <!-- the entity is X -->
    <pattern id="9">
      <dep FE="Orientation" pred="true" lexUnit="true" order="2">
        <dep FE="Entity" reln="nsubj" order="1"/>
      </dep>
    </pattern>
    <!-- The X entity -->
    <pattern id="10">
      <dep FE="Entity" tag="NOUN" order="2">
        <dep FE="Orientation" pred="true" reln="amod" lexUnit="true" order="1"/>
      </dep>
    </pattern>
    <!--TODO: how to add very specific lexical patterns e.g. upside down -->
    <!-- The entity is upside down -->
    <pattern id="11">
      <dep FE="Orientation" pred="true" word="down" order="3">
        <dep FE="Entity" reln="nsubj" order="1"/>
        <dep reln="advmod" word="upside" order="2"/>
      </dep>
    </pattern>
    <!-- ;;================================================================================
    ;; posture/orientation
    ;;================================================================================ -->
    <!-- TODO: do these really work for all verbs? should we have lemma="face"? a new frame for facing?   -->
    <!-- ;; "the boy faces the house"
(:match ((?rel :subject ?subj :direct-object ?val))
 :types ((?rel :we.orientation-face.r))
 :output ((?rel :entity ?subj :target ?val))) -->
    <!-- NOTE: this one also takes care of "facing northeast/southeast/southwest/west" TODO: what about different verbs?-->
    <pattern id="13">
      <dep tag="VERB" pred="true" lexUnit="true" order="2">
        <dep FE="Entity" reln="nsubj" order="1"/>
        <dep FE="Target" reln="dobj" order="3"/>
      </dep>
    </pattern>
    <!--  ;; "the boy faces to the north"
(:match ((?rel :subject ?subj :dep ?prep) (?prep :object-of-prep ?target))
 :types ((?rel :we.orientation-face.r))
 :output ((?rel :entity ?subj :target ?target))) -->
    <!--- used by to and toward -->
    <pattern id="14">
      <dep tag="VERB" pred="true" not-lemma="tilt|lean" order="2">
        <dep FE="Entity" reln="nsubj" order="1"/>
        <dep FE="Target" reln="nmod" order="4">
          <dep reln="case" lexUnit="true" order="3"/>
        </dep>
      </dep>
    </pattern>
    <!-- ;; "the boy is facing forward"
(:match ((?rel :subject ?subj :adverb ?adv))
 :types ((?rel :we.orientation-face.r)
         (?adv t))
 :strict-kb-match ((:we.adverb-to-entity.r :adverb ?adv :entity ?val))
 :output ((?rel :entity ?subj :target ?val))) -->
    <!-- TODO: a new frame for direction? -->
    <pattern id="15">
      <dep tag="VERB" pred="true" order="2">
        <dep reln="nsubj" FE="Entity" order="1"/>
        <dep FE="Target" reln="advmod" lexUnit="true" order="3"/>
      </dep>
    </pattern>
    <pattern id="16">
      <dep tag="VERB" pred="true" order="2">
        <dep reln="nsubj" FE="Entity" order="1"/>
        <dep FE="Target" reln="compound" lexUnit="true" order="3"/>
      </dep>
    </pattern>
    <!-- entity Xes toward the target -->
    <pattern id="25">
      <dep lexUnit="true" pred="true" order="2">
        <dep FE="Entity" reln="nsubj|nsubjpass" order="1"/>
        <exclude-dep reln="dobj"/>
        <dep FE="Target" reln="nmod" order="4">
          <dep reln="case" word="toward|to" order="3"/>
        </dep>
      </dep>
    </pattern>
    <!-- entity Xes count unit toward the target -->
    <pattern id="26">
      <dep lexUnit="true" pred="true" order="2">
        <dep FE="Entity" reln="nsubj|nsubjpass" order="1"/>
        <dep FE="Unit" reln="dobj" order="4">
          <dep FE="Count" reln="nummod" order="3"/>
        </dep>
        <dep FE="Target" reln="nmod" order="6">
          <dep reln="case" word="toward|to" order="5"/>
        </dep>
      </dep>
    </pattern>
  </valencePatterns>
  <lexUnit name="face-down.a">
    <lexeme tag="ADJ" word="face-down"/>
    <use-pattern id="8"/>
    <use-pattern id="9"/>
  </lexUnit>
  <lexUnit name="face-up.a">
    <lexeme tag="ADJ" word="face-up"/>
    <use-pattern id="8"/>
    <use-pattern id="9"/>
  </lexUnit>
  <lexUnit name="prostrate.a">
    <lexeme tag="ADJ" word="prostrate"/>
    <use-pattern id="8"/>
    <use-pattern id="9"/>
  </lexUnit>
  <lexUnit name="rightside-up.a">
    <lexeme tag="ADJ" word="rightside-up"/>
    <use-pattern id="8"/>
    <use-pattern id="9"/>
  </lexUnit>
  <lexUnit name="sideways.a">
    <lexeme tag="ADV" word="sideways"/>
    <lexeme tag="ADJ" word="sideways"/>
    <use-pattern id="8"/>
    <use-pattern id="9"/>
  </lexUnit>
  <lexUnit name="supine.a">
    <lexeme tag="ADJ" word="supine"/>
    <use-pattern id="8"/>
    <use-pattern id="9"/>
  </lexUnit>
  <lexUnit name="upright.a">
    <lexeme tag="ADJ" word="upright"/>
    <use-pattern id="10"/>
    <use-pattern id="9"/>
  </lexUnit>
  <lexUnit name="upside-down.a">
    <lexeme tag="ADJ" word="upside-down"/>
    <use-pattern id="10"/>
    <use-pattern id="9"/>
    <use-pattern id="11"/>
  </lexUnit>
  <lexUnit name="face.v">
    <lexeme tag="VERB" lemma="face"/>
    <use-pattern id="13"/>
  </lexUnit>
  <lexUnit name="toward.adp">
    <lexeme tag="ADP" word="toward"/>
    <lexeme tag="ADP" word="towards"/>
    <use-pattern id="14"/>
  </lexUnit>
  <lexUnit name="to.adp">
    <lexeme tag="ADP" word="to"/>
    <use-pattern id="14"/>
  </lexUnit>
  <!-- TODO: check with other verbs besides facing -->
  <lexUnit name="forward.adv">
    <lexeme tag="ADV" word="forward"/>
    <use-pattern id="15"/>
  </lexUnit>
  <lexUnit name="backward.adv">
    <lexeme tag="ADV" word="backward"/>
    <use-pattern id="15"/>
  </lexUnit>
  <lexUnit name="down.adp">
    <lexeme tag="ADP" word="down"/>
    <use-pattern id="16"/>
  </lexUnit>
  <lexUnit name="left.v">
    <lexeme tag="VERB" word="left"/>
    <use-pattern id="16"/>
  </lexUnit>
  <lexUnit name="right.adv">
    <lexeme tag="ADV" word="right"/>
    <use-pattern id="15"/>
  </lexUnit>
  <lexUnit name="up.adp">
    <lexeme tag="ADP" word="up"/>
    <use-pattern id="16"/>
  </lexUnit>
  <lexUnit name="east.a">
    <lexeme tag="ADJ" word="east"/>
    <use-pattern id="15"/>
  </lexUnit>
  <lexUnit name="north.adv">
    <lexeme tag="ADV" word="north"/>
    <use-pattern id="15"/>
  </lexUnit>
  <lexUnit name="northeast.adv">
    <lexeme tag="ADV" word="northeast"/>
    <use-pattern id="15"/>
  </lexUnit>
  <lexUnit name="northwest.adv">
    <lexeme tag="ADV" word="northwest"/>
    <use-pattern id="15"/>
  </lexUnit>
  <lexUnit name="south.adv">
    <lexeme tag="ADV" word="south"/>
    <use-pattern id="15"/>
  </lexUnit>

  <lexUnit name="lean.v">
    <lexeme lemma="lean" tag="VERB"/>
    <use-pattern id="25"/>
    <use-pattern id="26"/>
  </lexUnit>
  <lexUnit name="tilt.v">
    <lexeme lemma="tilt" tag="VERB"/>
    <use-pattern id="25"/>
    <use-pattern id="26"/>
  </lexUnit>
</frame>

=== mulinski/SpatialNet/SpatialNet/frames/Directional_locative_relation.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--frame cBy="JKR" cDate="11/30/2005 07:49:56 PST Wed" name="Artificiality" ID="1660" xsi:schemaLocation="../schema/frame.xsd" xmlns="http://framenet.icsi.berkeley.edu" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"-->
<frame name="Directional_locative_relation" xmlns="urn:spatialnet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:spatialnet frame.xsd">
  <parent name="Locative_relation"/>
  <FE name="Figure"/>
  <FE name="Ground"/>
  <!-- for distance -->
  <FE name="Count"/>
  <FE name="Unit"/>
  <FE name="Distance"/>
  <lexUnit name="above.adp">
    <lexeme tag="ADP" word="above"/>
    <use-pattern id="1"/>
    <use-pattern id="2"/>
    <use-pattern id="20"/>
  </lexUnit>
  <lexUnit name="below.adp">
    <lexeme tag="ADP" word="below"/>
    <use-pattern id="1"/>
    <use-pattern id="2"/>
    <use-pattern id="20"/>
  </lexUnit>
</frame>

=== mulinski/SpatialNet/SpatialNet/frames/Part_orientational.xml
<frame name="Part_orientational" xmlns="urn:spatialnet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:spatialnet frame.xsd">
  <parent name="Part_whole"/>
  <FE name="Part"/>
  <FE name="Whole"/>
  <valencePatterns>
    <!-- TODO: messing up on "the chair is right of the table." -->
    <!-- TODO: how to exclude "to the" as a unit -->
    <pattern id="12">
      <dep pred="true" FE="Part" tag="NOUN" order="1">
        <exclude-dep reln="case" word="to"/>
        <dep reln="nmod" FE="Whole" order="3">
          <dep reln="case" word="of" order="2"/>
        </dep>
      </dep>
    </pattern>
  </valencePatterns>
  <lexUnit name="DEFAULT">
    <use-pattern id="12"/>
  </lexUnit>
</frame>

=== mulinski/SpatialNet/SpatialNet/frames/Color.xml
<frame name="Color" xmlns="urn:spatialnet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:spatialnet frame.xsd">
  <parent name="Gradable_attributes"/>
  <FE name="Entity"/>
  <FE name="Attribute"/>
  <FE name="Color" parent="Value"/>
  <valencePatterns>
    <!-- the entity is color -->
    <pattern id="6">
      <dep pred="true" FE="Color" tag="ADJ" order="2">
        <dep FE="Entity" reln="nsubj" order="1"/>
      </dep>
    </pattern>
    <!-- the color entity -->
    <pattern id="7">
      <dep FE="Entity" tag="NOUN" order="2">
        <dep pred="true" FE="Color" reln="amod" order="1"/>
      </dep>
    </pattern>
  </valencePatterns>
  <lexUnit name="DEFAULT">
    <use-pattern id="6"/>
    <use-pattern id="7"/>
  </lexUnit>
  <!--lexUnit name="color.a">
  </lexUnit-->
</frame>

=== mulinski/SpatialNet/SpatialNet/frames/Measure_of_distance_and_length.xml
<frame name="Measure_of_distance_and_length" xmlns="urn:spatialnet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:spatialnet frame.xsd">
  <FE name="Count"/>
  <FE name="Unit"/>
  <valencePatterns>
    <pattern id="29">
      <dep tag="NOUN" FE="Unit" order="2">
        <dep FE="Count" reln="nummod" order="1"/>
      </dep>
    </pattern>
  </valencePatterns>
  <!--lexUnit name="block.n">
    <lexeme lemma="block" tag="NOUN"/>
    <use-pattern id="29"/>
  </lexUnit-->
  <lexUnit name="centimeter.n">
    <lexeme lemma="centimeter" tag="NOUN"/>
    <use-pattern id="29"/>
  </lexUnit>
  <lexUnit name="foot.n">
    <lexeme lemma="foot" tag="NOUN"/>
    <use-pattern id="29"/>
  </lexUnit>
  <!-- TODO: furlong -->
  <lexUnit name="inch.n">
    <lexeme lemma="inch" tag="NOUN"/>
    <use-pattern id="29"/>
  </lexUnit>
  <lexUnit name="kilometer.n">
    <lexeme lemma="kilometer" tag="NOUN"/>
    <use-pattern id="29"/>
  </lexUnit>
  <!-- TODO: light-year.n -->
  <lexUnit name="meter.n">
    <lexeme lemma="meter" tag="NOUN"/>
    <use-pattern id="29"/>
  </lexUnit>
  <lexUnit name="mile.n">
    <lexeme lemma="mile" tag="NOUN"/>
    <use-pattern id="29"/>
  </lexUnit>
  <lexUnit name="millimeter.n">
    <lexeme lemma="millimeter" tag="NOUN"/>
    <use-pattern id="29"/>
  </lexUnit>
  <lexUnit name="yard.n">
    <lexeme lemma="yard" tag="NOUN"/>
    <use-pattern id="29"/>
  </lexUnit>

</frame>

=== mulinski/SpatialNet/SpatialNet/frames/Locative_relation.xml
<frame name="Locative_relation" xmlns="urn:spatialnet" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:spatialnet frame.xsd">
  <FE name="Figure"/>
  <FE name="Ground"/>
  <!-- for distance -->
  <FE name="Count"/>
  <FE name="Unit"/>
  <FE name="Distance"/>
  <valencePatterns>
    <!-- The *fig* *rel* the *ground* -->
    <pattern id="1">
      <dep FE="Ground" tag="NOUN" order="3">
        <dep FE="Figure" reln="nsubj" order="1"/>
        <dep pred="true" reln="case" lexUnit="true" order="2"/>
      </dep>
    </pattern>
    <!-- The *fig* IS *rel* the *ground* -->
    <!-- This also handles "there is a fig on the ground -->
    <pattern id="2">
      <dep tag="VERB" pred="true" not-lemma="lean|tilt|hang" order="2">
        <dep FE="Figure" reln="nsubj" order="1"/>
        <dep FE="Ground" reln="nmod" order="4">
          <dep reln="case" lexUnit="true" order="3"/>
        </dep>
      </dep>
    </pattern>
    <!-- TODO: add "the dog that is 10 feet over the ground"-->
    <!-- TODO add "there is a dog 10 feet over the ground"-->
    <!-- fig is count unit rel the ground -->
    <pattern id="20">
      <dep tag="NOUN" FE="Unit" order="3">
        <dep FE="Figure" reln="nsubj" order="1"/>
        <dep FE="Count" reln="nummod" order="2"/>
        <dep FE="Ground" reln="nmod" order="5">
          <dep pred="true" reln="case" lexUnit="true" order="4"/>
        </dep>
      </dep>
    </pattern>
    <!--pattern id="20">
      <dep tag="NOUN" FE="Distance" order="2">
        <dep FE="Figure" reln="nsubj" order="1"/>
        <dep FE="Ground" reln="nmod" order="4">
          <dep pred="true" reln="case" lexUnit="true" order="3"/>
        </dep>
      </dep>
    </patterns-->
    <!-- fig is in the X of the ground -->
    <pattern id="22">
      <dep lexUnit="true" order="3">
        <dep reln="nsubj" FE="Figure" order="1"/>
        <dep reln="case" word="in" pred="true" order="2"/>
        <dep reln="nmod" FE="Ground" order="5">
          <dep reln="case" word="of" order="4"/>
        </dep>
      </dep>
    </pattern>
  </valencePatterns>

  <lexUnit name="middle.n">
    <lexeme tag="NOUN" word="middle"/>
    <use-pattern id="22"/>
  </lexUnit>
  <lexUnit name="center.n">
    <lexeme tag="NOUN" word="center"/>
    <use-pattern id="22"/>
  </lexUnit>
  <!--TODO: vignettes for around-->
  <lexUnit name="around.adp">
    <lexeme tag="ADP" word="around"/>
    <use-pattern id="1"/>
    <use-pattern id="2"/>
  </lexUnit>
</frame>
